import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans bg-gradient-to-b from-black via-black to-gray-900 min-h-screen`}
      >
        <header className="w-full p-4 bg-black/40 backdrop-blur border-b border-white/10 z-50 relative">
          <nav className="w-full p-4 bg-black/40 backdrop-blur border-b border-white/10">
            <Link href="/" className="text-white font-semibold mr-4">
              Inicio
            </Link>
            <Link href="/products" className="text-white font-semibold mr-4">
              Productos
            </Link>
            <Link href="/simulator" className="text-white font-semibold mr-4">
              Simulador
            </Link>
            <Link href="/onboarding" className="text-white font-semibold mr-4">
              Onboarding
            </Link>
          </nav>
        </header>

        <main className="w-full max-w-3xl mx-auto px-4 py-6">{children}</main>
        <footer className="text-center text-gray-500 text-sm py-6 ">
          © 2025 BCS – Prueba técnica realizada por Miguel Urquijo
        </footer>
      </body>
    </html>
  )
}
